workflows:
  # ============================================
  # RECOMMENDED: Unsigned IPA for Sideloading
  # This workflow creates an unsigned IPA that can be signed later
  # Perfect for jailbroken devices or manual signing with tools like iOS App Signer
  # ============================================
  ios-unsigned-workflow:
    name: iOS Penrion (Unsigned for Sideloading)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "ios-app/OsuTablet/OsuTablet.xcodeproj"
        XCODE_SCHEME: "OsuTablet"
      xcode: 15.0
    scripts:
      - name: Set up build environment
        script: |
          echo "Building unsigned IPA for sideloading..."
          echo "Project: $XCODE_PROJECT"
          echo "Scheme: $XCODE_SCHEME"
      
      - name: Configure project for unsigned build
        script: |
          cd ios-app/OsuTablet
          
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.penrion.osutablet" OsuTablet/Info.plist || true
          
          # Modify project settings to disable code signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' OsuTablet.xcodeproj/project.pbxproj || true
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' OsuTablet.xcodeproj/project.pbxproj || true
          
          echo "✓ Project configured for unsigned build"
          
      - name: Build app for iOS device
        script: |
          set -euo pipefail
          cd ios-app/OsuTablet
          
          # Build for device without code signing
          set -o pipefail
          xcodebuild clean build \
            -project OsuTablet.xcodeproj \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE="" \
            | xcpretty
          
          echo "✓ Build completed"
      
      - name: Create unsigned IPA package
        script: |
          set -euo pipefail
          cd ios-app/OsuTablet

          # Prefer .app from our local DerivedData path
          LOCAL_APP_PATH=$(find build/DerivedData/Build/Products/Release-iphoneos -maxdepth 2 -name "*.app" -type d | head -1 || true)

          if [ -n "$LOCAL_APP_PATH" ] && [ -d "$LOCAL_APP_PATH" ]; then
            APP_PATH="$LOCAL_APP_PATH"
          else
            # Fallback: determine from build settings (may point to global DerivedData)
            APP_DIR=$(xcodebuild \
              -project OsuTablet.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -showBuildSettings | awk -F" = " '/TARGET_BUILD_DIR/ {print $2}' | tail -1)

            WRAPPER_NAME=$(xcodebuild \
              -project OsuTablet.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -showBuildSettings | awk -F" = " '/WRAPPER_NAME/ {print $2}' | tail -1)

            APP_PATH="${APP_DIR:+$APP_DIR/}${WRAPPER_NAME}"
          fi

          echo "LOCAL_APP_PATH=$LOCAL_APP_PATH"
          echo "Resolved APP_PATH=$APP_PATH"

          if [ -z "$APP_PATH" ] || [ ! -d "$APP_PATH" ]; then
            echo "❌ Error: Could not find built .app directory"
            echo "Listing candidates under build/DerivedData:"
            find build/DerivedData -type d -name "*.app" | sed 's/^/Found: /' || true
            exit 1
          fi

          # Prepare Payload and create IPA
          rm -rf build/Payload
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/

          cd build
          zip -qry Penrion-OsuTablet-Unsigned.ipa Payload

          # Move IPA to repo release directory
          mkdir -p ../../release/ios
          mv -f Penrion-OsuTablet-Unsigned.ipa ../../release/ios/

          echo "✓ IPA created at: $(pwd)/../../release/ios/Penrion-OsuTablet-Unsigned.ipa"

      - name: Verify IPA
        script: |
          set -euo pipefail
          echo "PWD=$(pwd)"
          ls -la
          echo "Listing release directory:" 
          ls -la release || true
          echo "Listing release/ios directory:" 
          ls -la release/ios || true
          test -f "release/ios/Penrion-OsuTablet-Unsigned.ipa"
          echo "✅ Build successful!"
          ls -lh "release/ios/Penrion-OsuTablet-Unsigned.ipa"

    artifacts:
      - release/ios/*.ipa
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # ============================================
  # Alias workflow for tools referencing "ios-workflow"
  # Same as ios-unsigned-workflow, kept for compatibility
  # ============================================
  ios-workflow:
    name: iOS Penrion (Unsigned alias for compatibility)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "ios-app/OsuTablet/OsuTablet.xcodeproj"
        XCODE_SCHEME: "OsuTablet"
      xcode: 15.0
    scripts:
      - name: Set up build environment
        script: |
          echo "Building unsigned IPA for sideloading (ios-workflow alias)..."
          echo "Project: $XCODE_PROJECT"
          echo "Scheme: $XCODE_SCHEME"
      - name: Configure project for unsigned build
        script: |
          cd ios-app/OsuTablet
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.penrion.osutablet" OsuTablet/Info.plist || true
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' OsuTablet.xcodeproj/project.pbxproj || true
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' OsuTablet.xcodeproj/project.pbxproj || true
      - name: Build app for iOS device
        script: |
          set -euo pipefail
          cd ios-app/OsuTablet
          set -o pipefail
          xcodebuild clean build \
            -project OsuTablet.xcodeproj \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE="" \
            | xcpretty
      - name: Create unsigned IPA package
        script: |
          set -euo pipefail
          cd ios-app/OsuTablet

          LOCAL_APP_PATH=$(find build/DerivedData/Build/Products/Release-iphoneos -maxdepth 2 -name "*.app" -type d | head -1 || true)
          if [ -n "$LOCAL_APP_PATH" ] && [ -d "$LOCAL_APP_PATH" ]; then
            APP_PATH="$LOCAL_APP_PATH"
          else
            APP_DIR=$(xcodebuild \
              -project OsuTablet.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -showBuildSettings | awk -F" = " '/TARGET_BUILD_DIR/ {print $2}' | tail -1)
            WRAPPER_NAME=$(xcodebuild \
              -project OsuTablet.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -showBuildSettings | awk -F" = " '/WRAPPER_NAME/ {print $2}' | tail -1)
            APP_PATH="${APP_DIR:+$APP_DIR/}${WRAPPER_NAME}"
          fi

          echo "Resolved APP_PATH=$APP_PATH"
          test -n "$APP_PATH" && [ -d "$APP_PATH" ]

          rm -rf build/Payload
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/

          cd build
          zip -qry Penrion-OsuTablet-Unsigned.ipa Payload
          mkdir -p ../../release/ios
          mv -f Penrion-OsuTablet-Unsigned.ipa ../../release/ios/
      - name: Verify IPA
        script: |
          set -euo pipefail
          test -f "release/ios/Penrion-OsuTablet-Unsigned.ipa"
          echo "✅ Build successful!"
          ls -lh "release/ios/Penrion-OsuTablet-Unsigned.ipa"
    artifacts:
      - release/ios/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
